[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true

[plugin]
append_preloaders = [
    { mime = "text/*", run = "bat" },
    { mime = "application/json", run = "bat" }
]

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
    { run = 'vim "$@"', block = true, for = "unix" },
    { run = 'cmd /c "where nvim >nul 2>nul && nvim %* || vim %*"', block = true, for = "windows" }
]

[open]
rules = [
    { name = "*", use = "edit" }
]
