[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true

[tasks]
suppress_preload = true


[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "nvim", for = "unix" },
    { run = 'vim "$@"', block = true, desc = "vim", for = "unix" },
    { run = 'cmd /c "where nvim >nul 2>nul && nvim %* || vim %*"', block = true, desc = "nvim", for = "windows" },
    { run = 'nvim "%*"', block = true, desc = "nvim", for = "windows" },
    { run = 'vim "%*"', block = true, desc = "vim", for = "windows" }
]

[open]
prepend_rules = [
    { mime = "*", use = "edit" },
    { url = "*", use = "edit" }
]
