[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = true

[tasks]
suppress_preload = true


[opener]
edit = [
    { run = 'nvim %s', block = true, desc = "nvim" },
    { run = 'vim %s', block = true, desc = "vim" }
]

[open]
rules = [
    { url = "*", use = "edit" }
]
