[general]
live_config_reload = true
ipc_socket = true
import = [
  "theme.toml"
]

[terminal]
osc52 = "CopyPaste"

[window]
dimensions = { columns = 110, lines = 32 }
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "Full"
opacity = 0.93
blur = true
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.5
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600
unfocused_hollow = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Space",    mods = "Control",                         chars = "\x00" },
  { key = "N",        mods = "Control|Shift",                   action = "CreateNewWindow" },
  { key = "F11",                                                action = "ToggleFullscreen" },
  { key = "Return",   mods = "Alt",                             action = "ToggleFullscreen" },
  { key = "V",        mods = "Control|Shift",                   action = "Paste" },
  { key = "C",        mods = "Control|Shift",                   action = "Copy" },
  { key = "F",        mods = "Control|Shift", mode = "~Search", action = "SearchForward" },
  { key = "B",        mods = "Control|Shift", mode = "~Search", action = "SearchBackward" },
  { key = "Equals",   mods = "Control",                         action = "IncreaseFontSize" },
  { key = "Plus",     mods = "Control|Shift",                   action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",                         action = "DecreaseFontSize" },
  { key = "Key0",     mods = "Control",                         action = "ResetFontSize" },
  { key = "PageUp",   mods = "Shift",         mode = "~Alt",    action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift",         mode = "~Alt",    action = "ScrollPageDown" },
  { key = "Home",     mods = "Shift",         mode = "~Alt",    action = "ScrollToTop" },
  { key = "End",      mods = "Shift",         mode = "~Alt",    action = "ScrollToBottom" },
]
